default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: eLearning_development

test:
  <<: *default
  database: eLearning_test
production:
  <<: *default
  database: eLearning_production
  username: eLearning
  password: <%= ENV['ELEARNING_DATABASE_PASSWORD'] %>
